CREATE TABLE IF NOT EXISTS schueler (
  id SERIAL PRIMARY KEY,
  vorname VARCHAR(100) NOT NULL,
  nachname VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  passwort VARCHAR(255) NOT NULL,
  klasse VARCHAR(50) NOT NULL,
  geburtsdatum DATE,
  premium BOOLEAN DEFAULT FALSE,
  erstellt_am TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);